### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by CTNotch** [michaelknigge/pclparaphernalia#2]
Hey Michael:

This is not a bug report, rather a thank you.  I'm sorry that I contacted you in this manner, but I could not find another way.

I just wanted to thank you for posting the information about Chris, I have been following him for a long time and when his software went offline, I got concerned.  I have been scouring for information about him for months, today I learned that DansdadUK and Chris were the same person.  Makes me so sad that we lost him, he was truly an outstanding person.

Also, thank you for continuing his effort with his software.  I'm pretty versed in PCL and i-Series and I found information he post very helpful.  If I can be of any help to you please let me know.  I would like to see his work continued.

Pauli

**Comment by michaelknigge** [comment]
Pauli,

thank you. It's not my daily business to "play around" with PCL - but from time to tie I need to. So I myself was very happy that we've been able the get the source from Chris' Notebook and I was able to compile it.

Any useful suggestion and contribution is welcome.


Bye,
Michael
