### ISSUE TITLE
PCL looks good but jpeg is blank

### ISSUE THREAD

**Issue by smithachalla** [michaelknigge/pclparaphernalia#3]
I have a bitmap that is generated from this sample
https://github.com/microsoft/Windows-driver-samples/tree/master/print/OEM%20Printer%20Customization%20Plug-in%20Samples/C%2B%2B/bitmap

Now I am trying to learn PCL so this project is super helpful. Thank you

The input is a simple word document which is printed to the bitmap driver on File Port. (attached is a png of the word)
Input to the driver is a word document. Once the prn is generated from bitmap driver, I renamed the extension to .bmp. Now the input to paraphernalia project is a .bmp. This is converted to a PCL. 

Now how to view the PCL (meaning to convert the PCL to tiff or jpeg) using paraphernalia.

I used ghost PCL to then convert PCL to jpeg  but its blank. (for test viewing purposes)

We have our a viewer which actually converts to TIFF but here I just want to actually view the PCL that has been generated

Thank you
![Test](https://user-images.githubusercontent.com/17037132/80923880-e575fd00-8d4b-11ea-8dfe-4144c5c7c296.png)

Please suggest.

**Comment by michaelknigge** [comment]
smithachalla,

if you think the problem is a result of the generated bitmap, I think it would be helpful if you provide the bitmap that you've used...

As already written by private mail, the problem might be the size of the bitmap.

Bye,
Michael

**Comment by michaelknigge** [comment]
No issue with pclparaphernalia....
